### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by mrsmithy121** [EdgarVaguencia/tstoApp#1]
npm install
npm WARN tstoapp@0.1.0 No repository field.
-MacBook-Air:tstoApp Admin$ pip install -r requirements.txt
Requirement already satisfied (use --upgrade to upgrade): ansicolors==1.0.2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied (use --upgrade to upgrade): configparser==3.5.0b2 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied (use --upgrade to upgrade): Django==1.9.4 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 3))
Collecting django-gulp==2.3.0 (from -r requirements.txt (line 4))
  Using cached django_gulp-2.3.0-py2.py3-none-any.whl
Collecting env-tools==2.0.0 (from -r requirements.txt (line 5))
  Using cached env_tools-2.0.0-py2.py3-none-any.whl
Collecting futures==3.0.3 (from -r requirements.txt (line 6))
  Using cached futures-3.0.3-py2-none-any.whl
Collecting protobuf==2.6.1 (from -r requirements.txt (line 7))
Collecting psutil==3.3.0 (from -r requirements.txt (line 8))
Collecting requests==2.9.1 (from -r requirements.txt (line 9))
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting six==1.10.0 (from -r requirements.txt (line 10))
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting tini==3.0.1 (from -r requirements.txt (line 11))
  Using cached tini-3.0.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from protobuf==2.6.1->-r requirements.txt (line 7))
Installing collected packages: six, tini, env-tools, psutil, futures, django-gulp, protobuf, requests
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1:
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip/req/req_set.py", line 736, in install
    requirement.uninstall(auto_confirm=True)
  File "/Library/Python/2.7/site-packages/pip/req/req_install.py", line 742, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/Library/Python/2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/Library/Python/2.7/site-packages/pip/utils/**init**.py", line 267, in renames
    shutil.move(old, new)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 131, in copy2
    copystat(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 103, in copystat
    os.chflags(dst, st.st_flags)
OSError: [Errno 1] Operation not permitted: '/var/folders/t1/fzgm5zx91nz111cp167_zkcw0000gn/T/pip-aAebyR-uninstall/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six-1.4.1-py2.7.egg-info'

**Comment by mrsmithy121** [comment]
Sudo doesn't change the error

**Comment by EdgarVaguencia** [comment]
Try using [virtualenv](https://virtualenvwrapper.readthedocs.io/en/latest/install.html)
- $ pip install virtualenvwrapper
  - $ export WORKON_HOME=$HOME/.virtualenvs
  - $ source /usr/local/bin/virtualenvwrapper.sh
- $ mkvirtualenv tstoApp
- $ workon tstoApp
- $ pip install -r requirements.txt
