### ISSUE TITLE
Error to execute manager.py

### ISSUE THREAD

**Issue by ghost** [EdgarVaguencia/tstoApp#2]
# ./manage.py runserver

Traceback (most recent call last):
  File "./manage.py", line 8, in <module>
    from django.core.management import execute_from_command_line
  File "/usr/lib/python2.6/site-packages/django/**init**.py", line 1, in <module>
    from django.utils.version import get_version
  File "/usr/lib/python2.6/site-packages/django/utils/version.py", line 7, in <module>
    from django.utils.lru_cache import lru_cache
  File "/usr/lib/python2.6/site-packages/django/utils/lru_cache.py", line 28
    fasttypes = {int, str, frozenset, type(None)},
                    ^
SyntaxError: invalid syntax

**Comment by mrsmithy121** [comment]
Same error
